### ISSUE TITLE
Some Wrong again

### ISSUE THREAD

**Issue by Yo-yo-ooo** [jserv/xv6-x86_64#11]
<img width="947" alt="image" src="https://github.com/jserv/xv6-x86_64/assets/98507772/badf911b-a637-487c-898d-fa7769cb5b3e">

**Comment by jserv** [comment]
@Yo-yo-ooo, Instead of uploading screenshot, please update the description of this issue in plain text.

**Comment by Yo-yo-ooo** [comment]
Well I followed the 'make' command to do it, but in the end it displayed fbn<Maxfile

**Comment by Yo-yo-ooo** [comment]
mkfs

**Comment by Yo-yo-ooo** [comment]
like https://github.com/jserv/xv6-x86_64/issues/5 you say,i try make OPT=-O1/make OPT=-O2/make OPT=-Os But it can't

**Comment by quamtum** [comment]
modify Makefile 
check UPROGS := \ 
remove some UPROGS suck as "usertests" then can build img
but after boot to xv6, will show message below:
xv6...

acpi: cpu#0 apicid 0
acpi: cpu#1 apicid 1
acpi: ioapic#0 @fec00000 id=0 base=0
cpu0: starting xv6
cpu1: starting
cpu0: starting
init: starting sh
$ sh
pid 3 sh: trap 6 err 0 on cpu 0 eip 0xe7d addr 0x0--kill proc
$ ls
pid 4 sh: trap 6 err 0 on cpu 0 eip 0xe7d addr 0x0--kill proc
